### ISSUE TITLE
Local P2P Pool update download error

### ISSUE THREAD

**Issue by epepper** [vertcoin/One-Click-Miner#1]
As the title suggests, I am having an issue downloading the P2P Pool update after updating to 1.1.2.0, I was running 1.0.7.0 and it was running fine, I update and now I can't run a pool locally.

**Comment by Robban1980** [comment]
Do you have any logs you want to show, or screenshots etc?

**Comment by zemrys** [comment]
Some people have experienced issues after updating from version 1.0.7.0. I recommend starting fresh by turning the OCM off, then delete everything in your My Documents\Vertcoin One-Click Miner directory.

**Comment by vampyren** [comment]
Dont work, i installed for the fist time and no show, its stuck on loading. Clear the documents folder and still nothing. 
No hashrate either even if i use another pool, something is broken in this version.

**Comment by vampyren** [comment]
After restart and clearing the files in documents folder the local p2pool started working. Hashrate shows 0 still.

**Comment by epepper** [comment]
@zemrys I managed to get the p2pool to install, but now it is saying "loading" when I select run local node. And I am not mining, all the settings are correct.

Also, the web interface is stuck on loading.

**Comment by epepper** [comment]
@Robban1980 My logs only go back to Sunday, before the issue

**Comment by epepper** [comment]
I was able to get the logs to load, here are my current logs for today.

- , Main() LoadSettings: OK.
- , Main() Check_RPC_Settings: OK.
- , Main() Update_P2Pool_Config: OK.
- , Main() Update_P2Pool_Config: OK.
- , Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:04:31 GMT, Main() UPnP: Only one usage of each socket address (protocol/network address/port) is normally permitted
- Mon, 02 Oct 2017 22:04:31 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:04:31 GMT, Main() UPnP: SET OK. Ports set: 9181,9347
- Mon, 02 Oct 2017 22:04:31 GMT, Main() Start_P2Pool: OK.
- Mon, 02 Oct 2017 22:04:31 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:04:33 GMT, Main() UPnP: Only one usage of each socket address (protocol/network address/port) is normally permitted
- Mon, 02 Oct 2017 22:04:33 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:04:33 GMT, Main() UPnP: SET OK. Ports set: 9181,9347
- Mon, 02 Oct 2017 22:04:33 GMT, Main() Start_P2Pool: OK.
- Mon, 02 Oct 2017 22:04:33 GMT, Main() Loaded: OK, V:1.1.2.0
- Mon, 02 Oct 2017 22:04:37 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:04:37 GMT, Main() Update_Miner_Config: OK.
- Mon, 02 Oct 2017 22:04:37 GMT, Main() Start_Miner: OK.
- Mon, 02 Oct 2017 22:05:02 GMT, Main() Kill_P2Pool: OK.
- Mon, 02 Oct 2017 22:05:02 GMT, Main() Check_RPC_Settings: OK.
- Mon, 02 Oct 2017 22:05:02 GMT, Main() Update_P2Pool_Config: OK.
- Mon, 02 Oct 2017 22:05:02 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:05:02 GMT, Main() UPnP: SET OK. Ports set: 9181,9347
- Mon, 02 Oct 2017 22:05:02 GMT, Main() Start_P2Pool: OK.
- Mon, 02 Oct 2017 22:05:02 GMT, Main() Kill_P2Pool: OK.
- Mon, 02 Oct 2017 22:05:03 GMT, Main() Check_RPC_Settings: OK.
- Mon, 02 Oct 2017 22:05:03 GMT, Main() Update_P2Pool_Config: OK.
- Mon, 02 Oct 2017 22:05:03 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:05:03 GMT, Main() UPnP: SET OK. Ports set: 9181,9347
- Mon, 02 Oct 2017 22:05:03 GMT, Main() Start_P2Pool: OK.
- Mon, 02 Oct 2017 22:05:11 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:05:20 GMT, P2PoolScanner(), Loaded: OK
- Mon, 02 Oct 2017 22:05:24 GMT, Network1Scanner(), Scan Completed: OK
- Mon, 02 Oct 2017 22:05:24 GMT, Network2Scanner(), Scan Completed: OK
- Mon, 02 Oct 2017 22:05:46 GMT, SaveScannerData(), Loaded: OK
- Mon, 02 Oct 2017 22:05:51 GMT, Settings() Loaded: OK.
- Mon, 02 Oct 2017 22:05:53 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:05:53 GMT, Settings() Closed: OK.
- Mon, 02 Oct 2017 22:05:55 GMT, Settings() Loaded: OK.
- Mon, 02 Oct 2017 22:05:57 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:05:57 GMT, Settings() Closed: OK.
- Mon, 02 Oct 2017 22:05:59 GMT, LoadP2PoolInterface(), Load Browser: OK
- Mon, 02 Oct 2017 22:07:15 GMT, MinerConfigToolStripMenuItem(), Load Miner Config: OK
- Mon, 02 Oct 2017 22:07:27 GMT, SystemLogToolStripMenuItem(), Load Miner Log: OK
- Mon, 02 Oct 2017 22:07:47 GMT, P2PoolConfigToolStripMenuItem(), Load P2Pool Config: OK
- Mon, 02 Oct 2017 22:08:07 GMT, Main() Download_Miner: Access to the path 'msvcr120.dll' is denied.
- Mon, 02 Oct 2017 22:08:07 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:08:07 GMT, Main() Download_Miner: Downloaded OK.
- Mon, 02 Oct 2017 22:08:10 GMT, Main() MinerDownloadCompleted: Value cannot be null.
Parameter name: destinationFileName
- Mon, 02 Oct 2017 22:08:10 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:08:10 GMT, Main() MinerDownloadCompleted: OK.
- Mon, 02 Oct 2017 22:08:17 GMT, Main() Download_Miner: Access to the path 'msvcr120.dll' is denied.
- Mon, 02 Oct 2017 22:08:17 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:08:17 GMT, Main() Download_Miner: Downloaded OK.
- Mon, 02 Oct 2017 22:08:19 GMT, Main() MinerDownloadCompleted: OK.
- Mon, 02 Oct 2017 22:08:24 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:08:26 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:08:26 GMT, Main() Kill_Miner: OK.
- Mon, 02 Oct 2017 22:08:29 GMT, Main() Download_Miner: Downloaded OK.
- Mon, 02 Oct 2017 22:08:33 GMT, Main() MinerDownloadCompleted: OK.
- Mon, 02 Oct 2017 22:08:46 GMT, Main() Download_Miner: WebClient does not support concurrent I/O operations.
- Mon, 02 Oct 2017 22:08:46 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:08:46 GMT, Main() Download_Miner: Downloaded OK.
- Mon, 02 Oct 2017 22:08:46 GMT, Main() MinerDownloadCompleted: OK.
- Mon, 02 Oct 2017 22:08:50 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:08:56 GMT, Main() Download_Miner: WebClient does not support concurrent I/O operations.
- Mon, 02 Oct 2017 22:08:56 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:08:56 GMT, Main() Download_Miner: Downloaded OK.
- Mon, 02 Oct 2017 22:08:58 GMT, Main() MinerDownloadCompleted: OK.
- Mon, 02 Oct 2017 22:09:03 GMT, Main() Download_Miner: WebClient does not support concurrent I/O operations.
- Mon, 02 Oct 2017 22:09:03 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:09:03 GMT, Main() Download_Miner: Downloaded OK.
- Mon, 02 Oct 2017 22:09:05 GMT, Main() MinerDownloadCompleted: OK.
- Mon, 02 Oct 2017 22:09:07 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:09:20 GMT, Main() Download_Miner: WebClient does not support concurrent I/O operations.
- Mon, 02 Oct 2017 22:09:20 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:09:20 GMT, Main() Download_Miner: Downloaded OK.
- Mon, 02 Oct 2017 22:09:23 GMT, Main() MinerDownloadCompleted: OK.
- Mon, 02 Oct 2017 22:09:26 GMT, Main() Download_Miner: WebClient does not support concurrent I/O operations.
- Mon, 02 Oct 2017 22:09:26 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:09:26 GMT, Main() Download_Miner: Downloaded OK.
- Mon, 02 Oct 2017 22:09:29 GMT, Main() MinerDownloadCompleted: OK.
- Mon, 02 Oct 2017 22:09:30 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:09:41 GMT, Main() Download_Miner: WebClient does not support concurrent I/O operations.
- Mon, 02 Oct 2017 22:09:41 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:09:41 GMT, Main() Download_Miner: Downloaded OK.
- Mon, 02 Oct 2017 22:09:44 GMT, Main() MinerDownloadCompleted: OK.
- Mon, 02 Oct 2017 22:09:49 GMT, Main() Download_Miner: WebClient does not support concurrent I/O operations.
- Mon, 02 Oct 2017 22:09:49 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:09:49 GMT, Main() Download_Miner: Downloaded OK.
- Mon, 02 Oct 2017 22:09:51 GMT, Main() MinerDownloadCompleted: OK.
- Mon, 02 Oct 2017 22:09:53 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:09:54 GMT, Main() Kill_P2Pool: OK.
- Mon, 02 Oct 2017 22:09:58 GMT, Main() Download_Miner: WebClient does not support concurrent I/O operations.
- Mon, 02 Oct 2017 22:09:58 GMT, Main() SaveSettings: OK.
- Mon, 02 Oct 2017 22:09:58 GMT, Main() Download_Miner: Downloaded OK.
- Mon, 02 Oct 2017 22:10:01 GMT, Main() MinerDownloadCompleted: OK.
- Mon, 02 Oct 2017 22:10:42 GMT, Main(), Closed: OK

**Comment by Robban1980** [comment]
Looking at the log it seems like you keep downloading the miner. This would suggest that your antivirus is removing the miner.  Did you check it's quarantine?

**Comment by epepper** [comment]
@Robban1980 Not downloading the miner, installing the updates rather.

**Comment by vampyren** [comment]
Started using https://github.com/vertcoin/vertminer-nvidia/releases
Works so much better.

**Comment by zemrys** [comment]
Issue attributed to Virus Scanner/Firewall preventing download/extraction of p2pool files.  Closing thread.
