### ISSUE TITLE
mining_port is not updating

### ISSUE THREAD

**Issue by BobbyGR** [vertcoin/One-Click-Miner#10]
I was working on a way to let people know they are in a wrong pool by changing the MH/s to a color and using a tooltip window to tell them why it's red or green using the Update_Miner_Text() function.

I hit a snag when I attempted to see what he results are for 9181.  The mining_port() never updates or changes from 9171.  

When I swap between pools and put a simple MsgBox(mining_port) I never see it moving from 9171.

**Comment by zemrys** [comment]
The mining_port variable is used for hosting a p2pool node.  It won't have any affect on the pools you add manually or via the scanner.

**Comment by BobbyGR** [comment]
Any good way to snag what port is being used during mining?  Other than reading the config file?  was hoping mining_port was updated per, but seeing how it's locked in to the json....it would be great if we could tell people if they are in the wrong pool (that's the end goal of this). Not sure if you have something already in the works.  But Network 1 and lower than 100 MH/s == BadTime.    But then again, people could go to any pool with any port with this.  So I guess it doesn't matter....Came to the same conclusion when it came to trying to help people put in a correct wallet address....Some pools want you to use something other than your vertcoin ID. So..yay...we can't protect stupid.

**Comment by zemrys** [comment]
Yeah exactly that's where it gets tricky because there is no guarantee that the p2pool node they are mining to is using the default port settings, or that they are even mining to p2pool at all.

**Comment by zemrys** [comment]
I'm going to go ahead and call this issue closed for now.
