### ISSUE TITLE
AMD RX580 Does Not Mine Vertcoin One-Click Miner

### ISSUE THREAD

**Issue by CrumpyCrittor** [vertcoin/One-Click-Miner#101]
When using AMDlyclminer option on One-Click Miner and pressing start.
I get the following:
Failed to create a Lyra buffer. Device(Ellesmere) Platform index(0)
Failed to initialise device(0) Skipping...
the command prompt pop-up window closes.
I tried many possible fixes. Except the build lyclminer. I will be trying it next as mention of the lyclminer readme file on GitHub, but I don't see why I should have to install OpenCL premake5, or any other software other than the One-click Miner to get basic functionality of the AMDlyclminer option. I'm starting to think my RX580 doesn't like me or I got a faulty RX580.
I have the adrenaline driver.
I have 16GB virtual memory (swap)
I have edited the config.bat and created a configGenerate.dat
what else could I do?

I cannot find a config file solution that works, maybe their is one out their. I did get a config to work for my local pool. and I didn't need a config for the CPU to mine Local and P2Pool on other pools.

Is anyone else getting this issue?

I would one day love to use my RX580 with OneClickMiner to mine some Vertcoin.
CPU mining works and I got my local p2pool to work after finding which config file to duplicate and the correct directory to duplicate it to. 

Updated the AMDlyclminer software ok when I tried to launch AMDlyclminer for first time.

**Comment by zemrys** [comment]
Please try the latest version of Lyclminer offered via the OCM and see if that makes a difference for you.
