### ISSUE TITLE
NVidia ccminer don't start

### ISSUE THREAD

**Issue by Kazing** [vertcoin/One-Click-Miner#102]
When I try to start mining; OCM propose to download an update for cc miner.
After the download I try to start the mining on ccminer; but the mining doesn't start.

OCM version 1.2.0.0
The one click log: 
- 2018-07-21T09:42:02.2138871Z, Download_Miner: Download Started
- 2018-07-21T09:42:20.6941201Z, Client_MinerDownloadCompleted: MinerDownloadCompleted: OK.
- 2018-07-21T09:42:20.7037987Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-07-21T09:42:24.9742402Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-07-21T09:42:24.9742402Z, Update_Miner_Config: Update_Miner_Config: OK.
- 2018-07-21T09:42:26.0356769Z, Start_Miner: System.ComponentModel.Win32Exception (0x80004005): Accès refusé
 à System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
 à System.Diagnostics.Process.Start()
 à System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
 à VertcoinOneClickMiner.Main.Start_Miner()
- 2018-07-21T09:42:26.0356769Z, Start_Miner: Start_Miner: OK.

**Comment by lordgamegenie** [comment]
Same issue. Does not start. 
My Question to the devs.  What version of CCminer is this tool using?  Does incorporate at least CUDA 8.0 toolkit?

**Comment by zemrys** [comment]
This issue is likely caused by security software (firewalls, scanners, etc.) preventing access to the miner executable files.  Please make an exception for the OCM in such software.  You may need to make an exception for the OCM's working directory, which can be found at My Documents/Vertcoin One-Click Miner.
