### ISSUE TITLE
Adress

### ISSUE THREAD

**Issue by BigBil** [vertcoin/One-Click-Miner#103]
Dear,

I had decided yesterday after successfully mincing in other currencies of pools, going minning in vertcoin, so said so done, on the official website the vertcoin wallet downloaded, and the one clik miner.

I mined about 16 hours with + 300 mhs I have received 0.00000 VTC on catpool.io, and the Share Difficulty, Time to Share, Predicted Payout, stays at 0000000, then I'm not going to find any faq or help on the pool, not on the website of vertcoin, that's how I ended up here.

I have seen on the internet that there are false addresses of vtc,
That a VTC address starts with the letter V, my addresses created in the vertcoin core wallet downloaded from the vertcoin website, start with the letters 38 and 34.

I think it's a shame that a layman like me who still does not know the English language enough can find no explanation on the vertcoin website and especially on the pool where you can find no help or explanation in mine, and no faq.

Greetings

Geert

**Comment by BigBil** [comment]
Hi,
I know that I am a stupid person, and do not know anything about it, but I had expected an answer here, with some help.
Greetings

**Comment by zemrys** [comment]
Not all mining pools accept the new address format, including p2pool until we push the next update.  You will need to generate a "legacy" VTC address using **[this](https://i.imgur.com/cVuZIOK.png)** method.  Use the address generated for all of your VTC mining to avoid this problem in the future.

For future reference, any immediate support should be differed to our [Discord](https://discordapp.com/invite/vertcoin).

**Comment by bhoktodev44** [comment]
![screenshot_20181001-125402](https://user-images.githubusercontent.com/43526871/46450911-9d7ca600-c7b5-11e8-8e51-4257257f71db.png)
![screenshot_20181001-125410](https://user-images.githubusercontent.com/43526871/46450914-9d7ca600-c7b5-11e8-9e96-59a15e506d62.png)
![screenshot_20181001-125435](https://user-images.githubusercontent.com/43526871/46450915-9e153c80-c7b5-11e8-9c57-60c4a481e6fe.png)
![screenshot_20181001-125512](https://user-images.githubusercontent.com/43526871/46450916-9eadd300-c7b5-11e8-8c1b-ddf756b154d8.png)
hhelp me for this screenshoots,my coinpaiments,account,
