### ISSUE TITLE
Will not generate a config file

### ISSUE THREAD

**Issue by seperatis** [vertcoin/One-Click-Miner#104]
This is pretty weird. I install OCM on one desktop with Win 10, no issues at all. But on the second Win 10 desktop, I installed it exactly the same as the first computer, but when I launch OCM from the desktop icon, it says "Can't find lyclMiner.conf"

On the first computer it must have auto-generated one because I never made one manually.

I have tried like in the REAdme to make a GenerateConfig.bat with `lyclMiner -g lyclMiner.conf` inside the bat file. But when I launch it, it never creates the config file!

I'm ripping my freaking hair out here, I've un-installed and re-installed like 10 times now. What the F is going on?

**Comment by zemrys** [comment]
Please be sure you have the latest C++ redistributables installed.

https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by seperatis** [comment]
That link is for the 2015 version. I believe I have the 2017 version installed already. Do I specifically need the 2015 version? When I try to download and install from that link you gave me, it gives me the following error message: `Error 0x80070666: Cannot install a product when a newer version is installed.`

**UPDATE**
I un-installed Vertcoin OCM, un-installed the C++ redistributable 2017, then installed the 2015 C++ redistributable version link that you sent me, then re-installed OCM, and am still having the exact same issue. If never generates a config file, and I am still unable to do so manually. This is so confusing. The other Windows 10 Pro PC that I successfully installed OCM on with no issues is almost exactly the same configuration as this PC that OCM is giving me problems on.....

**Comment by nerdy2188** [comment]
sounds like anti virus to me.

**Comment by zemrys** [comment]
The Lyclminer configs are generated automatically by the OCM upon its launch.  It sounds like there is something wrong with the installation of either the drivers for your card or potentially the dependencies required to run it.  It's hard to say exactly what is going on, but in my eyes it is likely something to do with the C++ redis not being installed properly.  If these things aren't all working, the OCM cannot automate the creation of the config file by the miner's executable.
