### ISSUE TITLE
"Find P2Pool Node Scanner" doesn't sort in numerical order (again)

### ISSUE THREAD

**Issue by fgrueninger** [vertcoin/One-Click-Miner#108]
Same issue as reported in #47. Tested with 1.2.2.0.

![image](https://user-images.githubusercontent.com/33499883/52159468-4e804800-26a5-11e9-9d54-bdfcc76ec112.png)

**Comment by zemrys** [comment]
Fix by P2PoolMiner merged.  This fix will be available in the next release or now if you build yourself.
