### ISSUE TITLE
Removing all pools

### ISSUE THREAD

**Issue by waylandc** [vertcoin/One-Click-Miner#12]
I selected all added pools, and clicked Remove button while my miner was already running. I got an error message about invalid range which I assume means that must be at least 1 pool present. I clicked continue on that error message and the GUI closes (which is fine) but the console window that was running ocm_vertminer.exe continues to run.

You might want to disallow removing all pools or if you do, stop the ocm_vertminer process.

**Comment by waylandc** [comment]
In addition, when I restarted OCM, all the previous pool addresses were still there even after I had chosen to remove them earlier. 

FYI "Remove Pool" also isn't working when I have multiple pools selected.

**Comment by BobbyGR** [comment]
Reviewing

**Comment by BobbyGR** [comment]
https://github.com/vertcoin/One-Click-Miner/pull/13

**Comment by zemrys** [comment]
There will be a fix implemented in the next update.  Thanks all for the help/contribution. Closing for now.
