### ISSUE TITLE
Spaces in Vertcoin data directory breaks p2pool function

### ISSUE THREAD

**Issue by xNul** [vertcoin/One-Click-Miner#14]
In order to make your own p2pool, you have to set the Vertcoin data directory which points to the location where all of the block data is stored by Vertcoin Wallet Core.  If that directory has spaces, the p2pool software is not able to locate the directory.  This is because OCM does not append quotes around the directory when adding it to the batch file "start_p2pool.bat".

Here is the current, bugged, batch file (scroll to the right):
```batch
ocm_p2pool.exe --net vertcoin2 --give-author 0 --fee 0 --address VeF59DRaRuDiRVNgHvJn3nVpU6raik67Qk --max-conns 50 --worker-port 9181 --p2pool-port 9347 --bitcoind-config-path D:\Programs\Vertcoin Wallet\Data\vertcoin.conf
exit /B
```

Here is how it should look (scroll to the right):
```batch
ocm_p2pool.exe --net vertcoin2 --give-author 0 --fee 0 --address VeF59DRaRuDiRVNgHvJn3nVpU6raik67Qk --max-conns 50 --worker-port 9181 --p2pool-port 9347 --bitcoind-config-path "D:\Programs\Vertcoin Wallet\Data\vertcoin.conf"
exit /B
```

This bug is even more annoying because OCM tries to change the batch file back to the bugged way constantly.  You have to make a copy of the batch file with a different name and then run it independently of OCM.

**Comment by zemrys** [comment]
A fix will be available in the next update.
