### ISSUE TITLE
401 unauthorized

### ISSUE THREAD

**Issue by ade** [vertcoin/One-Click-Miner#16]
Hi, when I ran a local p2pool, I got an error in the console 401 Unauthorized

I was also spammed with the "parameter cannot be null, parameter: s" error, not sure if that was correlated (issue #11 )

I think the issue was with the auto-generated user pass in vertcoin core. Once I changed them to a new random user/pass, I stopped getting that error.

The problem user/pass was combo was:
`rpcuser=MCXqYAo!3sDSaeW$byQ4Um5#t
rpcpassword=#RFMd1PqeIDRCMyZWJ5%&0vlo`

I suspect the percent or dollar sign was not properly parsed via command line.

**Comment by zemrys** [comment]
Could you post the text that is contained within the settings.json file located within the My Documents\Vertcoin One-Click Miner directory?  Be sure to remove any information that you may want kept personal.

**Comment by ade** [comment]
I deleted it, but I can try to recreate the conditions if you want.

**Comment by zemrys** [comment]
If you can that would be great.  The "parameter cannot be null, parameter: s" error has been elusive and nobody has been providing any information to work from.

**Comment by ade** [comment]
I didn't get the parameter error again, sorry.

**Comment by zemrys** [comment]
Closing. "401 Unauthorized" error is not a direct issue with the OCM and a patch has been implemented to address the "parameter cannot be null, parameter: s" error.
