### ISSUE TITLE
Beta 1.1.6 endless update loop

### ISSUE THREAD

**Issue by ouifrenchy** [vertcoin/One-Click-Miner#20]
I have been mining just fine for a week or so. The One Click Miner just forced me to update to 1.1.6. I select NVIDIA miner and click Start. It says Update found for Nvidia Miner! I click OK. The miner downloads. It says Miner is ready to run. I click Start. back to Update found for Nvidia Miner!. Repeat infinitely. I have tried reboots, uninstall and fresh install, etc.

If I try CPU mining, I get An issue occurred during the download. Please try again.

- 2017-10-31T20:04:24.3486905Z, SaveSettingsJSON: SaveSettings: OK.
- 2017-10-31T20:04:24.3642934Z, LoadSettingsJSON: LoadSettings: OK.
- 2017-10-31T20:04:24.3955439Z, Form1_Load: Loaded: OK, V:1.1.6.0
- 2017-10-31T20:04:58.9497859Z, SaveSettingsJSON: SaveSettings: OK.
- 2017-10-31T20:05:26.3578305Z, SaveSettingsJSON: SaveSettings: OK.
- 2017-10-31T20:05:29.8479411Z, SaveSettingsJSON: SaveSettings: OK.
- 2017-10-31T20:05:31.3178011Z, Download_Miner: Downloaded OK.
- 2017-10-31T20:05:40.7999544Z, Client_MinerDownloadCompleted: MinerDownloadCompleted: OK.
- 2017-10-31T20:05:40.8155508Z, SaveSettingsJSON: SaveSettings: OK.
- 2017-10-31T20:05:42.5242091Z, SaveSettingsJSON: SaveSettings: OK.
- 2017-10-31T20:05:42.5398098Z, Update_Miner_Config: Update_Miner_Config: OK.
- 2017-10-31T20:05:42.5554363Z, Start_Miner: System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at VertcoinOneClickMiner.Main.Start_Miner()
- 2017-10-31T20:05:42.5554363Z, Start_Miner: Start_Miner: OK.
- 2017-10-31T20:05:44.5735588Z, SaveSettingsJSON: SaveSettings: OK.
- 2017-10-31T20:05:44.5735588Z, Update_Miner_Config: Update_Miner_Config: OK.
- 2017-10-31T20:05:44.6673278Z, Start_Miner: System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at VertcoinOneClickMiner.Main.Start_Miner()
- 2017-10-31T20:05:44.6673278Z, Start_Miner: Start_Miner: OK.
- 2017-10-31T20:05:46.5740194Z, SaveSettingsJSON: SaveSettings: OK.
- 2017-10-31T20:05:46.5894939Z, Update_Miner_Config: Update_Miner_Config: OK.
- 2017-10-31T20:05:46.5894939Z, Start_Miner: System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at VertcoinOneClickMiner.Main.Start_Miner()
- 2017-10-31T20:05:46.6051201Z, Start_Miner: Start_Miner: OK.
- 2017-10-31T20:05:48.3713591Z, SaveSettingsJSON: SaveSettings: OK.
- 2017-10-31T20:05:48.3871175Z, Update_Miner_Config: Update_Miner_Config: OK.
- 2017-10-31T20:05:48.4652931Z, Start_Miner: System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at VertcoinOneClickMiner.Main.Start_Miner()
- 2017-10-31T20:05:48.4652931Z, Start_Miner: Start_Miner: OK.
- 2017-10-31T20:05:50.2316745Z, SaveSettingsJSON: SaveSettings: OK.
- 2017-10-31T20:05:50.2471186Z, Update_Miner_Config: Update_Miner_Config: OK.
- 2017-10-31T20:05:50.2471186Z, Start_Miner: System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at VertcoinOneClickMiner.Main.Start_Miner()
- 2017-10-31T20:05:50.2627941Z, Start_Miner: Start_Miner: OK.
- 2017-10-31T20:05:58.7848630Z, SaveSettingsJSON: SaveSettings: OK.
- 2017-10-31T20:06:00.8944811Z, Download_Miner: Downloaded OK.
- 2017-10-31T20:06:16.9220156Z, Client_MinerDownloadCompleted: System.IO.FileNotFoundException: Could not find file '\\dosrv2\users\RFrench\Vertcoin One-Click Miner\nvidia\ocm_vertminer.exe'.
File name: '\\dosrv2\users\RFrench\Vertcoin One-Click Miner\nvidia\ocm_vertminer.exe'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at System.IO.File.OpenFile(String path, FileAccess access, SafeFileHandle& handle)
   at System.IO.File.SetLastWriteTimeUtc(String path, DateTime lastWriteTimeUtc)
   at System.IO.Compression.ZipFileExtensions.ExtractToFile(ZipArchiveEntry source, String destinationFileName, Boolean overwrite)
   at VertcoinOneClickMiner.Main.Client_MinerDownloadCompleted(Object sender, AsyncCompletedEventArgs e)
- 2017-10-31T20:06:16.9376120Z, SaveSettingsJSON: SaveSettings: OK.
- 2017-10-31T20:06:16.9376120Z, Client_MinerDownloadCompleted: MinerDownloadCompleted: OK.
- 2017-10-31T20:06:18.3596420Z, SaveSettingsJSON: SaveSettings: OK.
- 2017-10-31T20:06:20.6259835Z, SystemLogToolStripMenuItem_Click: SystemLogToolStripMenuItem(), Load Miner Log: OK
- 2017-10-31T20:10:11.4240176Z, SystemLogToolStripMenuItem_Click: SystemLogToolStripMenuItem(), Load Miner Log: OK
- 2017-10-31T20:10:17.6303559Z, Main_Closing: 

- 2017-10-31T20:10:17.6303559Z, Main_Closing: Closing: OK
- 2017-10-31T20:10:17.6457718Z, SaveSettingsJSON: SaveSettings: OK.
- 2017-10-31T20:10:17.6457718Z, Kill_Miner: Kill_Miner: OK.
- 2017-10-31T20:10:17.6614146Z, Kill_P2Pool: Kill_P2Pool: OK.
- 2017-10-31T20:10:17.6614146Z, Main_Closing: ================================================================================
- 2017-10-31T20:10:19.7562157Z, LoadSettingsJSON: LoadSettings: OK.
- 2017-10-31T20:10:19.7718175Z, Form1_Load: Loaded: OK, V:1.1.6.0
- 2017-10-31T20:10:22.3405448Z, SaveSettingsJSON: SaveSettings: OK.
- 2017-10-31T20:10:24.2642775Z, Download_Miner: Downloaded OK.
- 2017-10-31T20:11:05.5422586Z, Client_MinerDownloadCompleted: MinerDownloadCompleted: OK.
- 2017-10-31T20:11:05.5512820Z, SaveSettingsJSON: SaveSettings: OK.
- 2017-10-31T20:11:07.2350960Z, SaveSettingsJSON: SaveSettings: OK.
- 2017-10-31T20:11:08.9382148Z, SaveSettingsJSON: SaveSettings: OK.
- 2017-10-31T20:11:31.6703070Z, Main_Closing: 

- 2017-10-31T20:11:31.6703070Z, Main_Closing: Closing: OK
- 2017-10-31T20:11:31.6859381Z, SaveSettingsJSON: SaveSettings: OK.
- 2017-10-31T20:11:31.6859381Z, Kill_Miner: Kill_Miner: OK.
- 2017-10-31T20:11:31.7016411Z, Kill_P2Pool: Kill_P2Pool: OK.
- 2017-10-31T20:11:31.7016411Z, Main_Closing: ================================================================================
- 2017-10-31T20:11:45.3972386Z, LoadSettingsJSON: LoadSettings: OK.
- 2017-10-31T20:11:45.4284924Z, Form1_Load: Loaded: OK, V:1.1.6.0
- 2017-10-31T20:11:47.4290168Z, SaveSettingsJSON: SaveSettings: OK.
- 2017-10-31T20:11:49.1734517Z, Download_Miner: Downloaded OK.
- 2017-10-31T20:12:02.0327815Z, Client_MinerDownloadCompleted: MinerDownloadCompleted: OK.
- 2017-10-31T20:12:02.0483799Z, SaveSettingsJSON: SaveSettings: OK.
- 2017-10-31T20:12:48.1465310Z, SystemLogToolStripMenuItem_Click: SystemLogToolStripMenuItem(), Load Miner Log: OK

**Comment by zemrys** [comment]
Loops like this are generally caused by virus scanners/firewalls preventing the download and extraction of the new miner.  Be sure you have an exception listed for the OCM in Windows Defender and any other security measure you may be taking.

**Comment by ouifrenchy** [comment]
Watching \\dosrv2\users\RFrench\Vertcoin One-Click Miner\nvidia the file ocm_vertminer.exe shows up, then disappears.

**Comment by ouifrenchy** [comment]
Yes, looks like you are correct. TredMicro is quarantining it. Weird that it did not cause a problem on the previous release.

**Comment by zemrys** [comment]
Yeah it's hit and miss with the various scanners.  I'm working on circumventing these issues because they are obviously annoying to deal with whenever you install the OCM or an update is available.

**Comment by ouifrenchy** [comment]
Thank you for the quick response. Miner up!

**Comment by zemrys** [comment]
Anytime
