### ISSUE TITLE
illeagle memory  acsess detected

### ISSUE THREAD

**Issue by tusharkulkarni008** [vertcoin/One-Click-Miner#21]
![untitled](https://user-images.githubusercontent.com/4019737/32263248-2610c99e-be96-11e7-84a1-7dffc124d195.png)

**Comment by Sufuninja** [comment]
I have only ran into this issue while overclocking with improper settings.

**Comment by zemrys** [comment]
@Sufuninja is correct, this is usually due either to hardware error usually caused from overclocking or too high of an intensity setting. Closing issue.
