### ISSUE TITLE
Node Scanner hangs on high latency nodes

### ISSUE THREAD

**Issue by o-Epictetus-o** [vertcoin/One-Click-Miner#27]
Is there any way that we can have an option to specify how long a node has to respond when looking for servers? It shouldn't take more than 30 seconds to populate a node list. Better yet can we have an option to not even show nodes above a certain latency? Anything at this point would be better than nothing.

**Comment by zemrys** [comment]
I will look into this.

**Comment by zemrys** [comment]
This will be addressed in the next release.
