### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by Wootangy** [vertcoin/One-Click-Miner#29]
Any work or thoughts on making this available as a docker container in the future?
I'm sure a lot of people would love it!!

Thanks for this tool it's amazing and simple.

**Comment by Phiph** [comment]
Hi @Wootangy This project just serves as a GUI for downloading the respective miners for your CPU or GPUs, then adds the details needed to the configuration files. 

Unfortunately I can't envisage a way where you could take this project to manage Docker containers, or even be in a docker container. This may be treated as out-of-scope.

**Comment by zemrys** [comment]
This would be out-of-scope giving the nature of the OCM's usage.
