### ISSUE TITLE
When attempting to start mining with nvidia it fails to start.

### ISSUE THREAD

**Issue by pokepud3** [vertcoin/One-Click-Miner#30]
So I tried this with multiple different settings, and pools and it fails to start mining with the nvidia option. It simply starts up, shows the cli box, says waiting for share, and the cli box exits and it reverts to miner stopped. 

Somewhat related:  I use ethminer with cuda, and it's fine, so it's not a driver issue with the video card but oneclick miner. 

I used the cpu option and that mines.. albeit slow. I can't get the cli to stay open to see the error due to it exiting fast. My gpu is a GTX 970. Any idea how to troubleshoot this? Thanks.

**Comment by NotNOWTree** [comment]
Hello, 

I had the same problem to start with, had to turn off the "optimise for compute performance" setting in the Nvidia control panel (under the "Manage 3D settings") in order for it to work.

Might be worth a try.

Cheers

**Comment by pokepud3** [comment]
Yes that solved it perfectly! Thanks for the tip! (Might want to add that to the FAQ)

**Comment by NotNOWTree** [comment]
No worries buddy, glad it worked for you :)

**Comment by dhabibi** [comment]
I'm having this issue with a GTX 1070, except that setting does not appear under Manage 3D settings. Any ideas?

**Comment by snorrehaha** [comment]
I have the same problem with my GTX 970 and turning off "optimise for compute performance" does not help.

**Comment by Dewskerz** [comment]
I'm in the same boat as snorrehaha.  GTX 970, turning off that setting didn't help.

Anyone got any solutions?
