### ISSUE TITLE
Allow multiple instances so user can GPU and CPU mine at the same time

### ISSUE THREAD

**Issue by bendauphinee** [vertcoin/One-Click-Miner#31]
Currently, it seems that you can only mine with one.

**Comment by sterod** [comment]
+1 for now I've been manually running the CPU miner from a command prompt and the GPU miner in the the OCM window.

**Comment by lakozapamcenje** [comment]
With 8 nVidia and 5 ATI cards in a single rig, plus a powerful CPU - we need possibility to run 3 instances simultaneously.

**Comment by zemrys** [comment]
Adding this ability for a trial run in the next release.
