### ISSUE TITLE
Custom Miner Commands

### ISSUE THREAD

**Issue by sterod** [vertcoin/One-Click-Miner#33]
We need the ability to pass custom commands to the sgminer.  I opened the sgminer.conf file and added my changes, but it gets reverted back every time I start the miner.  I need to somehow pass on or add the **--gpu-platform 1** command to the config file so that it force detects my AMD GPU, without that switch, it only finds the onboard intel which I've already disabled in the BIOS.

**Comment by lakozapamcenje** [comment]
Same issue here - 8 AMD card rig, sgminer starts mining on integrated Intel only.

**Comment by zemrys** [comment]
Support for sgminer is limited as it stands now because it is so dated.  Once the new AMD miner is released (nextminer), the OCM will have all the needed functions incorporated.
