### ISSUE TITLE
Nvidia Fermi - Compute Capability 2.1  not supported?

### ISSUE THREAD

**Issue by francotheengineer** [vertcoin/One-Click-Miner#36]
Hi!

Does OCM support CUDA Compute Capability 2.1? It doesn't work on win10 64 when nvidia is selected, however, the amd/ati flavor works fine. 
 I assume it's based of vertminer-nvidia which doesn't not compile for CC 2.1 on ubuntu 17.04 .  I have tried altering the configuration files in vertminer-nvidia to no joy.

If there anything I can alter in the OCM code to compile for CC2.1?  

Many thanks

**Comment by zemrys** [comment]
No, the OCM is a wrapper for the miner software being used so it has no direct influence on GPU compatibility.
