### ISSUE TITLE
error during serialization or deserialization using the json javascript serializer

### ISSUE THREAD

**Issue by Bartjuhh83** [vertcoin/One-Click-Miner#37]
Hello,

im trying to connect my mining pc to network to but when im scanning for a pool i get this error.
![image](https://user-images.githubusercontent.com/10275099/33802560-1839988e-dd7a-11e7-8bed-431355fb29d6.png)
after that i can choose a pool on network 1 but network 2 is completely empty.
it worked before but now it seems there are too many pools?

any one else had this problem and found a fix for it?

**Comment by bradleynielsen** [comment]
Confirmed, just got it now with all updates.

**Comment by zemrys** [comment]
This issue has been fixed in version 1.1.7
