### ISSUE TITLE
p2p node scanner unable to scan Network 2

### ISSUE THREAD

**Issue by 1sid** [vertcoin/One-Click-Miner#38]
![image](https://user-images.githubusercontent.com/34423703/33808715-b0c7d4e8-ddf3-11e7-86a8-0581be1d6a3d.png)
Hi, 

I am setting up mining using one click miner on my pc running windows 10 and It doesn't scan the network 2 any help ?

**Comment by IlmLV** [comment]
same problem

**Comment by orddei** [comment]
same here =(

**Comment by zemrys** [comment]
The p2pool network has grown immensely, so the API call for the node scanner takes longer to process now.

**Comment by zemrys** [comment]
This has been updated/fixed in versions 1.1.6/1.1.7.

**Comment by sonny-life** [comment]
I receive "Unable to connect to P2Pool Network 2 Scanner API at this time." with 1.1.7.8
