### ISSUE TITLE
All Kinds of errors

### ISSUE THREAD

**Issue by manbearpigi** [vertcoin/One-Click-Miner#39]
![1](https://user-images.githubusercontent.com/34324653/33815374-8ca667a2-ddf6-11e7-8cc3-781bab1c9965.jpg)
![2](https://user-images.githubusercontent.com/34324653/33815375-8cb50c62-ddf6-11e7-9283-c0fe47f691e7.jpg)
![3](https://user-images.githubusercontent.com/34324653/33815376-8cc45d16-ddf6-11e7-9bd1-3c971b8e7cd3.jpg)
![4](https://user-images.githubusercontent.com/34324653/33815377-8cd45392-ddf6-11e7-9d17-a23abc70752a.jpg)
![5](https://user-images.githubusercontent.com/34324653/33815378-8ce34b18-ddf6-11e7-9755-762dcacb937c.jpg)
![6](https://user-images.githubusercontent.com/34324653/33815379-8cf1a686-ddf6-11e7-9985-c7267cd612a1.jpg)

**Comment by zemrys** [comment]
You likely have a virus scanner/firewall preventing directory access to the OCM.

**Comment by zemrys** [comment]
Closing due to dead thread.
