### ISSUE TITLE
Make the pool scanner use the port vs the ICMP 

### ISSUE THREAD

**Issue by BobbyGR** [vertcoin/One-Click-Miner#4]
As someone who doesn't enable ICMP on the internet firewall, I wanted a scanner that will give me the ms on an open port.  I used the stopwatch as a good example.  I could do a code push but more or less look what i've done below, seems to be working for me.

Also, this is faster than ICMP :), Granted if the port is closed to me it will "hang" on trying to open up the port, i'm guessing this can be adjusted with a timeout on the Net.Sockets.TcpClient()

`
Sub Scanner1Thread()

        'Network1 1
        Dim count As Integer = 0
        For x As Integer = 0 To scanner1.nodes.Count - 1
            Dim clientSocket As New Net.Sockets.TcpClient()
            Dim stopWatch As New Stopwatch()
            Try
                If stopthread = False And scanner1worker.ThreadState = ThreadState.Running Then
                    Try
                        stopWatch.Start()
                        clientSocket.Connect(scanner1.nodes(x).ip, "9171")
                        clientSocket.Close()
                        stopWatch.Stop()
                        DataGridView1.Rows(x).Cells(6).Value = stopWatch.ElapsedMilliseconds + "ms"
                    Catch ex As Exception
                        DataGridView1.Rows(x).Cells(6).Value = "Port Failed"
                    End Try
                Else
                    stopthread = False
                    Exit Sub
                End If
            Catch ex As Exception
            End Try
            count = x
        Next

    End Sub
`

**Comment by zemrys** [comment]
I'm catching an exception for every request with this code.

**Comment by BobbyGR** [comment]
Sorry, I just noticed I added the + ms at the end, remove that 

DataGridView1.Rows(x).Cells(6).Value = stopWatch.ElapsedMilliseconds

**Comment by BobbyGR** [comment]
This gives back the code with +ms+ added

`
 Sub Scanner1Thread()

        'Network1 1
        Dim count As Integer = 0
        For x As Integer = 0 To scanner1.nodes.Count - 1
            Dim clientSocket As New Net.Sockets.TcpClient()
            Dim stopWatch As New Stopwatch()
            Dim StopWatchTimeMs As String
            Try
                If stopthread = False And scanner1worker.ThreadState = ThreadState.Running Then
                    Try
                        stopWatch.Start()
                        clientSocket.Connect(scanner1.nodes(x).ip, "9171")
                        clientSocket.Close()
                        stopWatch.Stop()
                        StopWatchTimeMs = stopWatch.ElapsedMilliseconds
                        DataGridView1.Rows(x).Cells(6).Value = StopWatchTimeMs + "ms"
                    Catch ex As Exception
                        DataGridView1.Rows(x).Cells(6).Value = "Port Failed"
                    End Try
                Else
                    stopthread = False
                    Exit Sub
                End If
            Catch ex As Exception
            End Try
            count = x
        Next

    End Sub
`

**Comment by zemrys** [comment]
Ah I see, it's the + vs. &.  Everything is looking good on my end. Closing issue and merging pull request.

**Comment by zemrys** [comment]
Ah I see, it's the + vs. &. Everything is looking good on my end. Closing issue and merging pull request.
