### ISSUE TITLE
Abysmally low hashrates on nVidia P106-100

### ISSUE THREAD

**Issue by lakozapamcenje** [vertcoin/One-Click-Miner#41]
This card is a mining edition of GTX1060, equivalent in all specs, yet it only achieves 10-15MH/s. The very same card labeled as GTX1060 (with soldered-on DVI port) goes all the way up to 27MH/s...

I've tested this with dozens of different cards on two different systems, not a single P106 will go over 15MH/s.

What gives?

**Comment by zemrys** [comment]
The OCM is a wrapper for the miner software you are using and has no direct impact on your mining performance. I would recommend researching that particular card.  Join our [discord](https://discordapp.com/invite/Yb6EHNy) for mining support.
