### ISSUE TITLE
Unable to mine

### ISSUE THREAD

**Issue by jck0891** [vertcoin/One-Click-Miner#44]
I keep getting an error message saying 'Most likely you have input the wrong URL, forgotten to add a port, have not setup workers' I'm selecting from the 'find P2Pool Nodes' button and scanning for nodes so I don't see how the URL and port could be wrong and I'm copying my address from my electrum wallet so that should be fine also. What could be causing the issue?

Thanks

**Comment by RonBenner** [comment]
really seems like this is something nobody cares about anymore

**Comment by zemrys** [comment]
Could you be more specific as to what your issue is?  What exactly are you copying?  The latest version of the OCM (1.1.7.7) will prevent you from entering anything besides a valid VTC address via the Node Scanner function.

**Comment by zemrys** [comment]
Closed due to lack of response/dead thread.
