### ISSUE TITLE
VTC Segwit Wallet Compatible?

### ISSUE THREAD

**Issue by zconnolly** [vertcoin/One-Click-Miner#46]
Folks, how do we tell if we are supposed to use the segwit wallet or not if we are on devices like the ledger nano?  I was mining for a while before I checked the stats page and realized my time to payout stayed at 000. I noticed my wallet address did not start with V___ like all the others, and that of course was the issue.

Maybe some kind of verbiage in the help may save others some time on this.

If it is already mentioned somewhere, that I couldn't find, thanks anyway!

- Zak

**Comment by zemrys** [comment]
You're in the wrong place for wallet support.  Please join us on [Discord](https://discordapp.com/invite/Yb6EHNy) for help.

**Comment by zconnolly** [comment]
Gotcha!  Just a heads up -- my issue is already resolved, this was more of a request to put some text in the GUI help on the bottom right of the P2Pool Scanner page when entering wallet address (eg "Enter a *non-segwit* wallet address".  

Thanks for the info though!  Great app.
