### ISSUE TITLE
Sorting nodes by latency in "Find P2Pool Node Scanner" doesn't sort in numerical order

### ISSUE THREAD

**Issue by ghost** [vertcoin/One-Click-Miner#47]

**Comment by fgrueninger** [comment]
Works for me, except after hitting the issue described in https://github.com/vertcoin/One-Click-Miner/issues/37.

@BearerOfHonesty is sorting by latency *never* sorting in numerical order for you?

**Comment by ghost** [comment]
Havent't hit #37.

I tried messing around with it a bit more and it looks like it was just a coincidence with when I sorted and when the latency value showed up in the list so it looked like it had all been sorted but it was just some of the values that hadn't shown up yet so they didn't get sorted.

I seem to recall sorting several times after noticing the problem, so that shouldn't be a problem, but I can't reproduce it now either.

**Comment by fgrueninger** [comment]
Still happening in Beta 1.1.7.6:

![image](https://user-images.githubusercontent.com/33499883/34445035-a4dc8e8e-ecd1-11e7-91c5-3ca11e9a7495.png)

@BearerOfHonesty please reopen this issue :D

**Comment by zemrys** [comment]
The latency thread performs asynchronously to the scan itself, so if you sort the latency column while it is still pinging nodes you are likely to experience this issue.  Try sorting it again and you'll notice that it does sort numerically for the nodes that have already been pinged.

**Comment by fgrueninger** [comment]
The above screenshot has been taken a second after sorting - the latency has been sorted alphabetically, not numerical.

**Comment by zemrys** [comment]
Double-clicking the title bar sorts the latencies.  If you don't double-click, it won't sort them numerically.
