### ISSUE TITLE
Error while updating GPU miner

### ISSUE THREAD

**Issue by adarmiento** [vertcoin/One-Click-Miner#48]
Hello, I have this issue trying to use the miner. 
![error](https://user-images.githubusercontent.com/13642937/34072959-9b3bfebe-e290-11e7-8201-6f33f0fa184c.PNG)

What to do?
Thanks for the help

**Comment by zemrys** [comment]
This is likely caused by security software preventing the download/extraction of the miner.  Please check your virus scanners/firewalls and be sure to add an exception for the OCM.
