### ISSUE TITLE
Issue with running own node

### ISSUE THREAD

**Issue by MrBrighty** [vertcoin/One-Click-Miner#49]
Hello guys,

When i'm trying to put "x" into the checkbox for my own node running nothing happens. Actually there is a "loading" bar for 0,5 seconds then all comes back to the default set.  Screens attached.
What's most interesting, It worked some days... then this "magic' happened.  And yes, I've tried to set default settings already.

Will be appreciated for your response. 
EDIT: OCM doesn't work at all... the mining function acts also the same way - press the start - 0.5 seconds - nothing. It seems that  something happend with this app for this PC (yea, another OCM's at another PC's are working well). Is there is a way to delete totally all libs of this app? I'd like to reinstal the app. I've tried common way - to uninstal- to instal - It hasn't worked. 

![1](https://user-images.githubusercontent.com/19168046/34073596-dc539e6c-e2ad-11e7-8a0b-1265b6cd5c8c.jpg)
![2](https://user-images.githubusercontent.com/19168046/34073597-dc72edee-e2ad-11e7-8c35-a55bf36431ed.jpg)

**Comment by zemrys** [comment]
I'm not sure what you're experiencing or why.  You can delete the settings.json file located in the My Documents\Vertcoin One-Click Miner directory to force the OCM to start from scratch.

**Comment by Robban1980** [comment]
Confirm that your Vertcoin core wallet (still must be version 0.11 i think?) is running and fully synced before starting OCM and the P2pool node. This can cause issues. Also make sure you do not have any antivirus software blocking you.

For the miner part not working this is common in case you have antivirus that is deleting the files. McAfee for example will delete miners even if they are put on the exclusion list, every time a scan is performed.

**Comment by zemrys** [comment]
Closing issue due to thread silence.  Feel free to reopen if the issue persists.
