### ISSUE TITLE
Kill_Miner Access is Denied

### ISSUE THREAD

**Issue by howradisit** [vertcoin/One-Click-Miner#51]
When trying to stop the miner, I get:

- 2017-12-27T05:27:47.2415733Z, Kill_Miner: System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.Kill()
   at VertcoinOneClickMiner.Main.Kill_Miner()

I also notice it opens 2 ocm_sgminer.exe processes, not sure if it should be doing that or not.

**Comment by zemrys** [comment]
Which version are you running?

**Comment by howradisit** [comment]
1.1.7.3

**Comment by zemrys** [comment]
Are you using the 'Keep Miner Alive' option at all?

**Comment by howradisit** [comment]
I am not

**Comment by zemrys** [comment]
When you click 'Start' to start the miner process, is that when 2 sgminer windows pop up?

**Comment by howradisit** [comment]
The windows don't actually pop up, the processes start running in the background

**Comment by zemrys** [comment]
Alright I think I've got it traced.  I'll start debugging and include the fix in the next release.  Thanks for the input.

**Comment by howradisit** [comment]
The process is even started with my local account and can be stopped manually, if that helps

**Comment by howradisit** [comment]
Also, should there be 2 of them running?

**Comment by zemrys** [comment]
No there shouldn't.  This error is occurring because of the nature of sgminer.  Sgminer is so out of date that it is broken in some areas, requiring extra launch parameters to accommodate where it is lacking.  These parameters are interfering with how the OCM controls the miner process. I just put in a fix that I'll soon push to the beta download in the #oneclick channel of the Vertcoin Discord.

**Comment by zemrys** [comment]
Version 1.1.7.4 is posted in the #oneclick channel in our [Discord](https://discordapp.com/invite/Yb6EHNy).
