### ISSUE TITLE
Can't mine becaus updates for NVDIA AMD and CPU keep repeating

### ISSUE THREAD

**Issue by Bertv84** [vertcoin/One-Click-Miner#52]
When I click mine, the software gives me a message an update has been found. It downloads and installs with succes. But when I click to mine again another update downloads and installs... This keeps going...

**Comment by zemrys** [comment]
This is a known issue with security software outlined [here](https://github.com/vertcoin/One-Click-Miner/issues/22).  Please be sure to research your issue first before posting, or go to our Vertcoin Discord [HERE](https://discordapp.com/invite/Yb6EHNy) for direct support.
