### ISSUE TITLE
Trojan on one click miner VTC

### ISSUE THREAD

**Issue by Masterbinky** [vertcoin/One-Click-Miner#53]
First it was a virus, now it's a Trojan!
So I dont use this software untill You remove the Trojan!

**Comment by zemrys** [comment]
This is a known issue with security software outlined [here](https://github.com/vertcoin/One-Click-Miner/issues/22).  The OCM code is open source, we have nothing to hide. Please be sure to research your issue first before posting, or go to our Vertcoin Discord [HERE](https://discordapp.com/invite/Yb6EHNy) for direct support.
