### ISSUE TITLE
error

### ISSUE THREAD

**Issue by silverkaos** [vertcoin/One-Click-Miner#54]
launching the program I have this error ( i use win 7)
thanks

![cattura](https://user-images.githubusercontent.com/34964268/34455759-2332170e-ed86-11e7-8b86-7f3e9c0327ed.PNG)

**Comment by dusans** [comment]
Maybe try running OCM with admin rights. 
Are you using 32 or 64 bit windows?

**Comment by silverkaos** [comment]
i'm admin.
i use windows 64 bit
thanks

**Comment by dusans** [comment]
Maybe try to disable any antivirus you might be running.

**Comment by silverkaos** [comment]
I have done other tests:
if I use the command  -a lyra2rev2 the program goes wrong

example:
ocm_cpuminer -a lyra2rev2 -o stratum+tcp://xx -u xx -p xx


if I do not write "-a lyra2rev2" the program works
but I believe that the parameter is fundamental !!

thank for helps

**Comment by zemrys** [comment]
@silverkaos The OCM does not allow you to specify commands using cpuminer.  If you could provide translated logs/errors fo what you are experiencing I might be able to help further.

**Comment by DDblDD** [comment]
I get a similar error when attempting to launch a CPU mining session.
"ocm_cpuminer.exe has stopped working"

I'm running WIn10 64-bit.  I don't have an NVIDIA or AMD GPU installed in my computer.
I tried launching the application as "Administrator"

The SYSLOG.txt logfile shows
- 2018-01-28T18:09:52.0507198Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-01-28T18:09:52.2538551Z, Update_Miner_Config: Update_Miner_Config: OK.

In settings, I turned on the "Show CLI" option.
I see four lines every time before the application crashes:
"Starting Stratum on stratum+tcp://[Pools'sIPADDRESS]:9181
"2 miner threads started, using 'lyra2rev2' algorithm."
"Stratum difficulty set to 44.574 (0.17412)"
"lyra2rev block 867354, diff 30954.024"

Then the application error windows is displayed.

**Comment by vuongthinhpham** [comment]
Thinh0919

**Comment by jimrollings** [comment]
Any fix on this issue?

**Comment by zemrys** [comment]
Not as of yet.  There are different CPU miner builds for each generation of CPU processor, which makes it difficult to work for everyone's different hardware (likely what people are experiencing here).  I've planned on adding logic to detect the CPU and use the proper version of the miner, but since CPU mining for our algorithm is so inefficient/unprofitable it is not a very big priority.

**Comment by zemrys** [comment]
CPU mining is no longer supported by the OCM.
