### ISSUE TITLE
1.1.7.6 - Controls out of bounds

### ISSUE THREAD

**Issue by war4peace** [vertcoin/One-Click-Miner#55]
Hi,

I just installed 1.1.7.6 and this is how it looks like:

![image](https://user-images.githubusercontent.com/6294884/34457238-6888877a-edb3-11e7-8ab8-969ee77675bf.png)

I can't minimize the window or access most of the controls. 
Also I can't start mining, as soon as I click "Start" I get this, as a cascading error (multiple errors, going on forever):

![image](https://user-images.githubusercontent.com/6294884/34457249-c805b6dc-edb3-11e7-9cd1-f7c7b438b244.png)

I finally managed to close them and downloaded the miner (after a couple attempts, by the way the downloading miner window exceeds bounds as well), now it sort of works but the main window ontrol are off-screen as mentioned above.

Note: this was an update from previous version (1.1.6.0?)

**Comment by andyrew101** [comment]
I have the same issue, half of the UI is cut off. i installed previous versions and it corrects itself but now i get an error when i click start mining :/

**Comment by zemrys** [comment]
This is due to a bug caused by the 'Minimize to tray' feature.  There will be a fix included in the 1.1.7.7 release, but until then the best work around is to disable the above feature and restart the OCM.

**Comment by zemrys** [comment]
Version 1.1.7.7 has been released and contains fixes for your mentioned issue.
