### ISSUE TITLE
Run Local Node - RPC settings not updating configuration file

### ISSUE THREAD

**Issue by Mukrosz** [vertcoin/One-Click-Miner#57]
Hello,

I am trying to run a local node by pressing "Run Local Node".
I then receive "RPC settings(s) not found in wallet configuration file. Would you like Verticoin One-Click Miner to generate and append RPC settings to configuration file" for which I select OK.
I then receive "If your Vertcoin wallet is currently running, please close it and click OK" for which i click OK and the loop repeats, back to the "RPC..." message.

I've confirmed I do not have any Vertcoin wallet processes running and it still complains.

Can you please point me in the right direction :)

OCM: 1.1.7.6
Windows Vertcoin wallet: v0.12.0
Windows 7 64bit

Cheers!

**Comment by zemrys** [comment]
Thank you for the feedback.  This appears to be a confirmed bug that will be remedied in the next version.  I'll close this issue once a fix is available via the next release.

**Comment by Mukrosz** [comment]
Thank you:)
Any way I can circumvent it in the mean time?

**Comment by zemrys** [comment]
Rename or move the vertcoin.conf file located within your Vertcoin Core Data directory and try to launch p2pool from the OCM again.  It should prompt you with "Wallet configuration file not found, would you like Vertcoin One-Click Miner to create one?"  Click yes and then restart your core wallet.

**Comment by Mukrosz** [comment]
Thank you! that appears to have worked except I get a "Loading" under "Local P2Pool". Not sure if that is supposed to take a while

**Comment by zemrys** [comment]
You can select 'Show CLI' in the settings menu to see the miner and p2pool output windows.  Just be sure to restart the p2pool/miner process after changing the setting.  Version 1.1.7.7 is now available for download.  Either restart your OCM to prompt notification or click File > Update.
