### ISSUE TITLE
Local P2Pool Stuck in "Loading"

### ISSUE THREAD

**Issue by SankarPersaud** [vertcoin/One-Click-Miner#59]
I ran the Vertcoin core wallet, and it fully sync'd.  

I checked off 'run local node', and it's stuck on loading for over an hour.  Is that normal?

**Comment by SankarPersaud** [comment]
Here's the output from the cli:











[01:08:43] Started sgminer 5.1.0
[01:08:43] * using Jansson 2.7
[01:08:43] Loaded configuration file sgminer.conf
[01:08:43] WARNING: GPU_USE_SYNC_OBJECTS is not specified!

**Comment by zemrys** [comment]
@SankarPersaud Did you restart the core wallet after starting the node for the first time?  Also, you are posting the output from the AMDminer's window, not p2pool.  Until the new AMD miner is finished, there is very limited support available for the current AMD miner, sgminer.

**Comment by SankarPersaud** [comment]
restarted PC, restarted core wallet, all is well now. 

Thanks.
