### ISSUE TITLE
Auto start miner doesn't select a pool

### ISSUE THREAD

**Issue by NickBolles** [vertcoin/One-Click-Miner#6]
When the OCM is set to autostart and is restarted, no pools are selected so Vertminer crashes. Persisting the selection between runs of autostart would probably fix this.
![unknown 1](https://user-images.githubusercontent.com/7891759/31730249-fc5164e6-b3f6-11e7-9496-94f37661fd23.png)

**Comment by zemrys** [comment]
There will be a fix in the next version that addresses this issue.  Thank you for notifying!
