### ISSUE TITLE
access denied

### ISSUE THREAD

**Issue by cynicall** [vertcoin/One-Click-Miner#60]
"access to the path 'C:\Program Files (x86)\Vertcoin One-Click Miner\Settings.json' is denied.
  edit: went to path to find that settings.json does not exist there
  edit2: discovered that this only happens on the newest version

**Comment by cynicall** [comment]
just another heads up, i went to the path and the file settings.json does not even exist

**Comment by zemrys** [comment]
This is likely due to your security software locking the OCM out of it's working directories.  Make sure to make an exception in your firewall/virus scanner for the OCM.

**Comment by zemrys** [comment]
Please refer to issue [22](https://github.com/vertcoin/One-Click-Miner/issues/22).
