### ISSUE TITLE
Computer Freezing

### ISSUE THREAD

**Issue by sbowler** [vertcoin/One-Click-Miner#61]
After mining for a while, my computer keeps freezing. The monitors will be off and won't come back on. I can tell from the fan noise the computer is pretty idle and no longer mining.

I'm mining with an EVGA GTX 1070 FTW card on Windows 10. I'm unsure if this recent issue is due to Windows updates or an update with the miner. Is anyone else having any similar issues that have just cropped up recently?

**Comment by zemrys** [comment]
It looks to me like your GPU could be overheating, the intensity is set too high, a bad driver, or you have bad overclock settings.  Will the monitors wake at all, or do you require a restart?

**Comment by sbowler** [comment]
Just running the latest driver, but that's possible. I haven't overclocked it at all. The monitors will not turn on at all, have to restart the computer. I'm not aware of any intensity setting or anything like that, although it does seem to mine at a bit higher rate than it used to.

**Comment by zemrys** [comment]
It sounds to me like your GPU may be overheating.  I would start by going into the 'Settings' menu on the OCM and setting the intensity to 0 if it's not already.  If that doesn't help, you may want to look into installing software like MSI's Afterburner, so you can monitor your GPU and limit it's power consumption/ increase the fan speed.

**Comment by sbowler** [comment]
Ya, it's already at 0. I concur with your assessment. Was the intensity thing something added fairly recently? It does seem like it's mining like a Mh faster or so 2 than it used to. I'll look into doing as you suggest.

**Comment by zemrys** [comment]
The intensity setting has always been there.  The only recent major changes to the mining/p2pool process are the p2pool update to Vardiff and 0.12 wallet support.
