### ISSUE TITLE
unhandled exception error

### ISSUE THREAD

**Issue by Russ915** [vertcoin/One-Click-Miner#63]
![untitled](https://user-images.githubusercontent.com/34557019/34854784-c39a1d22-f709-11e7-89cc-0ad356625e88.png)

i keep getting this error, it seems to work if i force through, just wanted to bring to your attention

**Comment by zemrys** [comment]
This is likely due to your security software locking the OCM out of it's working directories. Make sure to make an exception in your firewall/virus scanner for the OCM.
Please refer to issue [22](https://github.com/vertcoin/One-Click-Miner/issues/22).
