### ISSUE TITLE
I can't deselect GPU

### ISSUE THREAD

**Issue by corautem** [vertcoin/One-Click-Miner#65]
I have a 5 gpus rig but only mine with 4, so I have gpu devices 0 to 4 with device 1 not for mining, on settings at devices I can select a maximum of 3 devices separated by comma (0,2,3) but to add them all I would need to use -  so if I use 0,2-4 i get an error like "non-existant cuda device '2-4' specified in -d option"
   If I write 0,2,3 it's working but is 1 gpu less
   If I leave it black it's working but it takes all 5 gpus and again is not ok.
   Any solutions, please.

**Comment by zemrys** [comment]
I don't think you are limited to listing just 3 devices via that option.  Did you try (0,2,3,4)? [Here](https://github.com/tpruvot/ccminer/blob/windows/README.txt#L132) is the readme for ccminer.  The "2-4" option may only be available for [sgminer](https://github.com/sgminer-dev/sgminer/blob/master/doc/configuration.md#device)

**Comment by corautem** [comment]
It doesn't allow me more then 5 characters to type in so it's not an option, I even tried to modifie via miner configuration option but once I hit start all settings revert back to default.

**Comment by zemrys** [comment]
You're right, the OCM is limiting that field to 5 characters.  I have fixed it and will include it in the next patch.

**Comment by corautem** [comment]
Thank you, really appreciated.

**Comment by vuongthinhpham** [comment]
#65
