### ISSUE TITLE
I know this is a "One-Click-Miner" but... any chance we can get a silent install string?

### ISSUE THREAD

**Issue by JesseHarris-Tanium** [vertcoin/One-Click-Miner#7]
I'd like to use the One Click Miner for one of my demos, but was hoping for a silent install string or a config file I can use to facilitate.

I'll send 20vtc your way :)

Much appreciated.

**Comment by zemrys** [comment]
Sorry, in the effort to prevent botnets and malicious use of the OCM we cannot facilitate.
