### ISSUE TITLE
One click miner error: access issues

### ISSUE THREAD

**Issue by KoenPeijnenborg** [vertcoin/One-Click-Miner#73]
Hello,

I'm trying to get the Vertcoin one click miner to run on my computer. I have succesfully installed version 1.1.7.8 in program files (x86). 
When I try to open the program, it gives me the following error message (translated to English): "Cannot access the indicated hardware, pad or file. It is possible you do not have the necessary access clearance."
I am admin of this computer, and have installed the program to "all users". 

What can I do to access the program? 

![image](https://user-images.githubusercontent.com/35566714/35100459-307ddaf8-fc5c-11e7-89a0-55ec28706181.png)

**Comment by zemrys** [comment]
Please refer to issue [60](https://github.com/vertcoin/One-Click-Miner/issues/60).
