### ISSUE TITLE
CPU-cpuminer hangs when starting miner

### ISSUE THREAD

**Issue by dardan88** [vertcoin/One-Click-Miner#75]
Log file shows:
- 2018-01-19T23:14:23.6747812Z, SaveSettingsJSON: SaveSettings: OK.
- 2018-01-19T23:14:23.6837883Z, Update_Miner_Config: Update_Miner_Config: OK.
- 2018-01-19T23:14:38.9646577Z, Start_Miner: System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at VertcoinOneClickMiner.Main.Start_Miner()
- 2018-01-19T23:14:38.9826693Z, Start_Miner: Start_Miner: OK.
- 2018-01-19T23:14:44.0005249Z, SystemLogToolStripMenuItem_Click: SystemLogToolStripMenuItem(), Load Miner Log: OK

I've checked file acls all look good. Any other idea's for troubleshooting?

**Comment by ghost** [comment]
@dardan88  If it's reporting ACCESS_DENIED- that doesn't necessarily mean the issue is related to ACLs. Is this issue still present?

**Comment by zemrys** [comment]
CPU mining is no longer supported by the OCM.
