### ISSUE TITLE
can I run this on ubuntu??

### ISSUE THREAD

**Issue by weiaicunzai** [vertcoin/One-Click-Miner#77]
hi, thx for your great work, I've downloaded the source code ,and notice that it was  written in vb and using vs, is there a cpp version of source code that I can compile and run it on a  ubuntu based machine??Thanks.

**Comment by zemrys** [comment]
Not currently, but you can convert it and try it for yourself if you're interested.

**Comment by weiaicunzai** [comment]
ok .thank you
