### ISSUE TITLE
Run Local Node - opens and closes immediately

### ISSUE THREAD

**Issue by wbkramit** [vertcoin/One-Click-Miner#78]
Ran update, using 1.1.7.9. When clicking run local node, the box immediately unclicks itself and the pool never gets started. Rebooted, reinstalled, updated to VTC wallet 12. Nothing helps.

**Comment by zemrys** [comment]
If you are still experiencing this issue, try deleting the p2pool folder found in My Documents\Vertcoin One-Click Miner.  The next time you try to start it, it will prompt you to update p2pool. Try this and see if it fixes your issue.
