### ISSUE TITLE
Amd Card stop mining today

### ISSUE THREAD

**Issue by GreenV154071** [vertcoin/One-Click-Miner#79]
My Amd Card just stop mining today. It still have the Crimson driver not the adrenaline

Please assist

**Comment by zemrys** [comment]
There is currently very limited AMD support for the OCM.  The current version of Sgminer does not play well with most modern AMD cards.  There is a new AMD miner in the works called Nextminer, and you can keep up with it's development progress by visiting the #nextminer channel in our [Discord](https://discordapp.com/invite/vertcoin), or by reading the dedicated update post on our [Subreddit](https://www.reddit.com/r/vertcoin/comments/7kih13/nextminer_open_source_miner_daily_updates/?utm_content=title&utm_medium=hot&utm_source=reddit&utm_name=vertcoin).
