### ISSUE TITLE
Trying to install OCM, click the .msi to install, "cannot find msi package"

### ISSUE THREAD

**Issue by reck614** [vertcoin/One-Click-Miner#80]
![screenshot 107](https://user-images.githubusercontent.com/36098714/35765335-c6f51636-0904-11e8-8d9f-0e96d43da103.png)
As the screenshot indicates. Keep getting this error and cannot install OCM.

**Comment by ghost** [comment]
You source you selected isn't a valid location

@reck614 have you resolved this yet?

**Comment by zemrys** [comment]
This is likely due to virus/firewall software quarantining the installer file.  Please make sure exceptions have been made in your security software to allow the OCM and it's miners to run.
