### ISSUE TITLE
Installer issue on Win10/64

### ISSUE THREAD

**Issue by staseo** [vertcoin/One-Click-Miner#82]
Installer issue on Win10/64:
![wtf](https://user-images.githubusercontent.com/36358392/36070959-41050ae8-0f0f-11e8-9fe4-bfd691d1682c.png)

**Comment by ghost** [comment]
@staseo have you tried running the application as admin? If not I'll compile you a custom build ASAP to temporarily resolve the issue until we can look into it more.

**Comment by staseo** [comment]
Hi Mathew,
Issue resolved. Right click on the .msi file >> uninstall. After that, the installation works.
Thnks

**Comment by ghost** [comment]
@staseo excellent. Issue noted!
