### ISSUE TITLE
AMD SGMiner won't start with RADEON RX570

### ISSUE THREAD

**Issue by cg4monty** [vertcoin/One-Click-Miner#89]
Running on Windows 7 64 bit.  Initially I was getting an "the program can't start because opencl.dll is missing from your computer". So, I copied the opencl.dll from my System folder into the AMD folder (w/in the OCM directory). The error went away but now I get a quick DOS prompt with a "Success: Specified Value was saved" message twice. The DOS prompt quickly disappears and the Miner status button moves from "stop" to "start".   I've tried both on the local pool/core wallet and with P2Pool addresses.  I'm a mining newbee but loved what this project stands for so I had to give it a try.  Any ideas ? 

 Bought the GPU card because I never could get OCM to work with the CPU miner.  Now, neither work.  Am I relegated to NVIDIA ?    Any help would be  appreciated.

**Comment by zemrys** [comment]
SGminer never worked very well for the Lyra2REv2 algorithm.  The OCM now utilizes Lyclminer, which fully supports mining Vertcoin.
