### ISSUE TITLE
Error Parsing Address ValueError(Substring Not Found) When Starting Local Node

### ISSUE THREAD

**Issue by laserlance** [vertcoin/One-Click-Miner#93]
I'm using wallet: Vertcoin Core version v0.13.0.0-1a4381e (64-bit) on Windows 10. I generate an address in the wallet, which starts with a "3", or a "vtc1" if I check "generate bech32 address"; the addresses look entirely different from every other VTC address I have seen, which usually start with an uppercase "V". When I put either the "3" address or the "vtc1" address into the "Settings"/fee address box of the One-Click Miner (version 1.1.8.0) and attempt to run the local node, the console window flashes open and then closes quickly. I was able to run the bat file without the exit command so that I could see what the problem was, which is when I saw the error "error parsing address: ValueError(substring not found).

I am able to connect to a P2Pool using the "3" address, but when doing so the "Time to Share" and "Share Difficulty" are all zeros. I have, however, sent VTC from an Electrum wallet to a "3" address with success, so it seems that there is some incompatibility with all of the different address types.

How does one generate a good ole fashioned "V" address from the latest version of the Vertcoin Core wallet? Everywhere I look I'm told I shouldn't mine with an Electrum wallet, or to an exchange, but they're the only ones that give me an address that works.

**Comment by zemrys** [comment]
This is likely due to the version of P2Pool that's being utilized not supporting the latest address formats.  The latest version of OCM (1.2.3.0) contains the latest version of P2Pool (post Lyra2REv3 fork), and will bring you current with that compatibility.
