### ISSUE TITLE
Vertcoin P2Pool Does not support P2SH or Bech32 Payout Addresses

### ISSUE THREAD

**Issue by digitalwav** [vertcoin/One-Click-Miner#99]
After updating to the latest version of:
-Vertcoin OCM v1.2.0.0
-Vertcoin Core Wallet v0.13.2.0-bc60034 (64-bit)
P2Pool fails to startup and closes out after a second or two. Digging deeper, the console is spitting out the error:

"usage: ocm_p2pool.exe [-h] [--version]
                      [--net {bitcoin,btcregtest,fastcoin,litecoin,terracoin,vertcoin,vertcoin2}]
                      [--testnet] [--debug] [-a ADDRESS] [-i NUMADDRESSES]
                      [-t TIMEADDRESSES] [--datadir DATADIR]
                      [--logfile LOGFILE] [--web-static WEB_STATIC]
                      [--merged MERGED_URLS]
                      [--give-author DONATION_PERCENTAGE] [--iocp]
                      [--irc-announce] [--no-bugreport] [--p2pool-port PORT]
                      [-n ADDR[:PORT]] [--disable-upnp] [--max-conns CONNS]
                      [--outgoing-conns CONNS] [--external-ip ADDR[:PORT]]
                      [--disable-advertise] [-w PORT or ADDR:PORT]
                      [-f FEE_PERCENTAGE]
                      [--miner-share-rate SHARES_PER_MINUTE]
                      [--address-share-rate SHARES_PER_MINUTE]
                      [--min-difficulty DIFFICULTY]
                      [--bitcoind-config-path BITCOIND_CONFIG_PATH]
                      [--bitcoind-address BITCOIND_ADDRESS]
                      [--bitcoind-rpc-port BITCOIND_RPC_PORT]
                      [--bitcoind-rpc-ssl]
                      [--bitcoind-p2p-port BITCOIND_P2P_PORT]
                      [BITCOIND_RPCUSERPASS [BITCOIND_RPCUSERPASS ...]]
**ocm_p2pool.exe: error: error parsing address: ValueError('address not for this net!',)**"

AND:

"Fatal error:
Traceback (most recent call last):
  File "twisted\internet\defer.pyc", line 567, in _startRunCallbacks

  File "twisted\internet\defer.pyc", line 653, in _runCallbacks

  File "twisted\internet\defer.pyc", line 1357, in gotResult

  File "twisted\internet\defer.pyc", line 1301, in _inlineCallbacks

--- <exception caught here> ---
  File "p2pool\main.pyc", line 145, in main

  File "p2pool\bitcoin\data.pyc", line 334, in address_to_pubkey_hash

**exceptions.ValueError: address not for this net!"**

A web search brings up this post on the Github page for P2Pool:
**"https://github.com/p2pool/p2pool/issues/378"**

It looks like the newest version of Vertcoin Core defaults to a new address format that is currently unsupported by P2Pool...

Anyone have any ideas on how to correct this issue or work around it, besides downgrading to the previous version of Vertcoin Core? Thanks!

**Comment by digitalwav** [comment]
If you keep digging you always find a solution!

Found this post: **"https://github.com/vertcoin-project/vertcoin-core/issues/48?ref=tokendaily"**

**"We're working on upgrading P2Pool to support the new address format. In the meantime you can generate a V address from the debug console using getnewaddress "" legacy."**

Hope this helps anyone with the same issue!

**Comment by zemrys** [comment]
P2Pool has since been updated with P2SH & Bech32 support.
